name: 'Scan'
on:
  schedule:
    - cron: '0 23 30 * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'owo what is this'
        required: false
        default: 'uwu what is this'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm start
